// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecprcjpqadauqbyakdlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjcHJjanBxYWRhdXFieWFrZGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NjY1OTYsImV4cCI6MjA1OTQ0MjU5Nn0.euSlrkgGW8cwNS64TSGuRhA3OyNfBVpboWFynQsxdio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);